### ISSUE TITLE
Weird error based on running location

### ISSUE THREAD

**Issue by krasimir** [metaskills/mocha-phantomjs#168] opened 2015-01-01 19:03 UTC
My `TestRunner.html` is placed in a `tests` folder. If I call `mocha-phantomjs tests/TestRunner.html` everything is fine. However, if I go to the `tests` folder and run `mocha-phantomjs ./TestRunner.html` I got
```
Failed to use load and use the custom reporter ...../code/todomvc/backbone/tests/spec.js
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///usr/local/lib/node_modules/mocha-phantomjs/lib/mocha-phantomjs.coffee. Domains, protocols and ports must match.
```

**Comment by nathanboktae** [comment] 2015-01-02 01:23
Looks like its similar to #167. Do you have a `mocha-phantomjs.opts` file in one folder vs. another? What about `TestRunner.html` vs. `./TestRunner.html`?

**Comment by krasimir** [comment] 2015-01-02 08:50
Hello,

a) Nope, I don't have `mocha-phantomjs.opts` file.
b) I tried both `TestRunner.html` and `./TestRunner.html`. The result is the same. 

Are you able to reproduce the problem. Maybe it is something with my local setup.

**Comment by cfmeyers** [comment] 2015-01-29 10:33
I'm having the same issue.  Running mocha-phantomjs 3.5.3, phantomjs 1.9.8, and I have no `mocha-phantomjs.opts` file.

**Comment by nathanboktae** [comment] 2015-01-31 18:41
What if you invoke phantom directly?

```
phantomjs your/path/to/lib/mocha-phantomjs.coffee TestRunner.html
```

**Comment by cdaringe** [comment] 2015-02-16 22:55
@nathanboktae--it renders the same error :(

**Comment by nathanboktae** [comment] 2015-02-16 23:35
Yeah I don't have enough information to help you. A publicly available repro of this issue would be appreciated.

**Comment by callumacrae** [comment] 2015-03-24 19:53
Here we go, failing in this repo:

https://github.com/callumacrae/whtevr
https://travis-ci.org/callumacrae/whtevr

**Comment by callumacrae** [comment] 2015-04-01 14:22
@nathanboktae Are you able to replicate? I'm getting the same error on another repo.

**Comment by callumacrae** [comment] 2015-04-02 16:19
I think my issue was caused by calling `mocha.run()` when I wanted to call `mochaPhantomJS.run()`.

https://github.com/callumacrae/whtevr/commit/0370bf6c14346b437075a319e203edc17b5befe2

**Comment by nathanboktae** [comment] 2015-05-14 06:19
Closing as a dupe of #167

**Closed by nathanboktae** 2015-05-14 06:19 UTC
